# Generated by Django 5.0 on 2024-01-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_generalsetting_generalsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralSettings',
            new_name='GeneralSetting',
        ),
    ]
