# Generated by Django 5.0 on 2024-01-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_generalsettings_generalsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='createdDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='updatedDate',
            field=models.DateField(auto_now=True),
        ),
    ]
