# Generated by Django 5.0 on 2024-01-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_skill_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedDate', models.DateField(auto_now=True, verbose_name='Updated Date')),
                ('createdDate', models.DateField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('link', models.URLField(blank=True, default='', max_length=255, verbose_name='Link')),
                ('icon', models.CharField(blank=True, default='', max_length=255, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
                'ordering': ('order',),
            },
        ),
    ]
