# Generated by Django 5.0 on 2024-01-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedDate', models.DateField(auto_now=True, verbose_name='Updated Date')),
                ('createdDate', models.DateField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, default='', max_length=255, null=True, verbose_name='Email')),
                ('subject', models.CharField(blank=True, default='', max_length=255, verbose_name='Subject')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
